/* Distinct training positions, contextual local coaching, and clear mic support feedback. */
const studyFens={openings:'r1bqkbnr/pp3ppp/2pp4/4p3/3PP3/2N2N2/PPP2PPP/R1BQKB1R w KQkq - 0 4',endgames:'8/8/8/8/8/4k3/3P4/4K3 w - - 0 1',tactics:'4k3/8/2q5/8/3N4/8/8/4K3 w - - 0 1',courses:'r3k2r/pppq1ppp/2n1bn2/3pp3/3PP3/2PB1N2/PP3PPP/R1BQ1RK1 w kq - 0 8'};
function study(page){if(studyFens[page])state.board=boardFromFen(studyFens[page])}
function imgPiece(p){const m={'♟':'bP','♞':'bN','♝':'bB','♜':'bR','♛':'bQ','♚':'bK','♙':'wP','♘':'wN','♗':'wB','♖':'wR','♕':'wQ','♔':'wK'};return m[p]?`<img class="piece-image" draggable="false" src="https://lichess1.org/assets/piece/cburnett/${m[p]}.svg" alt="">`:''}
boardHtml=function(board){let o='<div class="board-shell"><div class="player-bar"><span class="player-dot opponent"></span><b>Coach position</b><small>analysis board</small></div><div class="board" id="board">';for(let r=8;r>=1;r--)for(let f=0;f<8;f++){let sq=files[f]+r,p=board[sq]||'',cl=(f+r)%2?'dark':'light',sel=state.selectedSquare===sq?' selected':'',last=state.lastMove.includes(sq)?' last':'';o+=`<button class="sq ${cl}${sel}${last}" data-square="${sq}" aria-label="${p?`${p} on `:''}${sq}">${f===0?`<i class="rank">${r}</i>`:''}${r===1?`<i class="file">${files[f]}</i>`:''}${imgPiece(p)}</button>`}return o+`</div><div class="player-bar"><span class="player-dot you"></span><b>Aaravraohi</b><small>your board</small></div><div class="board-status"><span>WHITE TO MOVE</span><strong>${state.lastMove.length?'LAST: '+state.lastMove.join('–').toUpperCase():'STUDY POSITION'}</strong><span>CLASSIC</span></div></div>`}
endgames=function(){study('endgames');return training('ENDGAME COACH','Opposition: win the key squares','White to move. Which king route keeps the pawn protected and takes the opposition?','♚')}
tactics=function(){study('tactics');return training('TACTICS TRAINER','Find the loose piece','White to move. Black’s queen is exposed: which candidate move attacks it while improving your knight?','✦')}
openings=function(){study('openings');return `<section class="page"><div class="section-title"><p class="eyebrow">OPENING LAB · OPEN SICILIAN</p><h1>Develop, then strike.</h1><p>White to move after 1.e4 c5 2.Nf3 d6 3.d4 cxd4 4.Nxd4 e5. Which piece is least active and why?</p></div><div class="analysis-layout"><div class="board-wrap">${boardHtml(state.board)}<div class="board-controls"><button class="primary" data-action="stockfish">ANALYZE THIS POSITION</button><button class="outline" data-page="coach">ASK COACH</button></div></div>${coachPanel()}</div></section>`}
courses=function(){let c=[['01','Calculation Foundations','A development position. Find the forcing moves first.'],['02','The Open Sicilian','A real pawn structure: decide which piece needs development.'],['03','Rook Endgames','A king-and-pawn position where opposition matters.'],['04','Game Review Method','A tactical position: find the loose piece before the engine.']];return `<section class="page"><div class="section-title"><p class="eyebrow">CHESSCOACH CURRICULUM</p><h1>Learn with a plan, not a feed.</h1><p>Every lesson opens a distinct study position and a coaching question.</p></div><div class="course-grid">${c.map(x=>`<article class="panel course-card"><span class="number">COURSE ${x[0]}</span><h2>${x[1]}</h2><p>${x[2]}</p><button class="outline" data-action="course" data-course="${x[1]}">OPEN POSITION →</button></article>`).join('')}</div></section>`};views.courses=courses;
startMic=async function(){if(state.media.mic)return stopMic();if(!navigator.mediaDevices?.getUserMedia){alert('This browser does not support microphone access. Use current Chrome, Edge, or Safari over HTTPS.');return}try{state.media.mic=await navigator.mediaDevices.getUserMedia({audio:true});let R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){state.chat.push({role:'coach',text:'Microphone connected, but this browser has no built-in speech transcription. Try Chrome or Edge for live transcription.'});render();return}let rec=new R();rec.continuous=true;rec.interimResults=true;rec.onresult=e=>{if(!e.results[e.resultIndex].isFinal)return;let t=e.results[e.resultIndex][0].transcript.trim();if(t)askCoach(t,true)};rec.onerror=e=>alert('Speech transcription stopped: '+(e.error||'unknown browser error'));rec.start();state.media.recognition=rec;state.chat.push({role:'coach',text:'Microphone connected. I will transcribe your completed sentence and respond.'});say('Microphone connected. Tell me what you see on the board.');render()}catch(e){alert('Microphone permission was not granted. Check the address-bar microphone permission, then try again.')}};
askCoach=async function(raw,fromVoice=false){let q=raw.toLowerCase();state.chat.push({role:'user',text:escapeHtml(raw)});let reply=q.includes('best move')?'Press ANALYZE POSITION so Stockfish can calculate a verified line. First, list the checks and captures you see.':q.includes('bishop')?'Good candidate. Which bishop do you mean, and what square would make it more active?':q.includes('center')?'Exactly. Now ask whether the move improves a piece or creates a direct threat.':q.includes('weak')||q.includes('worst')?'Look for the piece with the fewest safe squares and least influence on the center. Which one is it?':'Useful observation. What is your opponent threatening on the next move?';let endpoint=window.CHESSCOACH_COACH_ENDPOINT;if(endpoint){try{let r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:raw,fen:fenFromBoard(),mode:'teacher'})});let d=await r.json();reply=d.reply||reply}catch(e){reply='Your hosted coach endpoint is unavailable, so the built-in study coach is active. What is the opponent threatening?'}}state.chat.push({role:'coach',text:reply});if(fromVoice||state.page==='call')say(reply);render()};
const bindBeforeFix=bind;bind=function(){bindBeforeFix();let f=document.querySelector('#chatForm');if(f)f.onsubmit=e=>{e.preventDefault();let i=document.querySelector('#chatInput');if(i.value.trim())askCoach(i.value)}};
render();
