/* Legal move enforcement is delegated to chess.js, never to board display state. */
if(typeof Chess!=='undefined'){
  state.chess=new Chess();state.initialFen=state.chess.fen();state.legalTargets=[];
  const symbol={p:'♟',n:'♞',b:'♝',r:'♜',q:'♛',k:'♚'};
  function syncBoard(){let out={};state.chess.board().forEach((row,ri)=>row.forEach((p,fi)=>{if(p){let s=symbol[p.type];out[files[fi]+(8-ri)]=p.color==='w'?{'♟':'♙','♞':'♘','♝':'♗','♜':'♖','♛':'♕','♚':'♔'}[s]:s}}));state.board=out}
  function loadRulesFen(fen){state.chess=new Chess(fen);state.initialFen=fen;state.selectedSquare=null;state.legalTargets=[];syncBoard()}
  const oldStudy=study;study=function(page){const real={endgames:'2K5/k1P5/8/8/8/8/7r/2R5 w - - 0 1',tactics:'4k3/8/2q5/8/3N4/8/8/4K3 w - - 0 1',openings:'r1bqkbnr/pp3ppp/2pp4/4p3/3PP3/2N2N2/PPP2PPP/R1BQKB1R w KQkq - 0 4',courses:'r3k2r/pppq1ppp/2n1bn2/3pp3/3PP3/2PB1N2/PP3PPP/R1BQ1RK1 w kq - 0 8'};if(real[page])loadRulesFen(real[page]);else oldStudy(page)};
  const oldBoard=boardHtml;boardHtml=function(board){let html=oldBoard(board);return html.replace(/class="sq ([^"]*)" data-square="([a-h][1-8])"/g,(all,classes,sq)=>`class="sq ${classes}${state.legalTargets?.includes(sq)?' legal':''}" data-square="${sq}"`)};
  moveSquare=function(sq){let p=state.chess.get(sq);if(!state.selectedSquare){if(!p||p.color!==state.chess.turn())return;state.selectedSquare=sq;state.legalTargets=state.chess.moves({square:sq,verbose:true}).map(m=>m.to);render();return}let from=state.selectedSquare;if(sq===from){state.selectedSquare=null;state.legalTargets=[];render();return}if(!state.legalTargets.includes(sq)){if(p&&p.color===state.chess.turn()){state.selectedSquare=sq;state.legalTargets=state.chess.moves({square:sq,verbose:true}).map(m=>m.to);render()}return}let move=state.chess.move({from,to:sq,promotion:'q'});state.lastMove=[from,sq];state.selectedSquare=null;state.legalTargets=[];syncBoard();state.chat.push({role:'coach',text:`${move.san} is legal. Before the next move: what changed in the position?`});render()};
  const previousAction=action;action=function(a){if(a==='reset'){loadRulesFen(state.initialFen||new Chess().fen());render();return}return previousAction(a)};
  endgames=function(){loadRulesFen('2K5/k1P5/8/8/8/8/7r/2R5 w - - 0 1');return `<section class="page"><div class="section-title"><p class="eyebrow">ENDGAME COACH · LUCENA</p><h1>Build a bridge, then free your king.</h1><p>White has king, rook and a c-pawn; Black’s king is cut off. White to move: find the rook move that starts the bridge plan.</p></div><div class="analysis-layout"><div class="board-wrap">${boardHtml(state.board)}<div class="board-controls"><button class="outline" data-action="reset">RESET LUCENA</button><button class="primary" data-action="stockfish">CHECK WITH ENGINE</button></div><div class="engine"><div class="engine-head"><span>ENDGAME IDEA</span><span>AUTHORED LESSON</span></div><p class="pv">In a Lucena position the stronger side shelters its king from checks by building a bridge. Compare this to Philidor: there the defender’s king blocks the pawn and the rook holds the third rank.</p></div></div>${coachPanel()}</div></section>`};
  views.endgames=endgames;views.tactics=tactics;views.openings=openings;views.courses=courses;
  render();
}
