/* Optional media is only requested after the user presses a call control. */
Object.assign(state,{engine:{status:'ready',eval:'—',depth:0,pv:'Press Analyze to run Stockfish.',worker:null},media:{mic:null,camera:null,recognition:null,voice:true}});
titles.courses='Courses';
function pieceClass(p){return p&&p.charCodeAt(0)>=9812&&p.charCodeAt(0)<=9817?'white':'black'}
boardHtml=function(board){let o='<div class="board-shell"><div class="player-bar"><span class="player-dot opponent"></span><b>Coach position</b><small>analysis board</small></div><div class="board" id="board">';for(let r=8;r>=1;r--)for(let f=0;f<8;f++){let sq=files[f]+r,p=board[sq]||'',cl=(f+r)%2?'dark':'light',sel=state.selectedSquare===sq?' selected':'',last=state.lastMove.includes(sq)?' last':'';o+=`<button class="sq ${cl}${sel}${last}" data-square="${sq}" aria-label="${sq}">${f===0?`<i class="rank">${r}</i>`:''}${r===1?`<i class="file">${files[f]}</i>`:''}${p?`<span class="piece ${pieceClass(p)}">${p}</span>`:''}</button>`}return o+`</div><div class="player-bar"><span class="player-dot you"></span><b>Aaravraohi</b><small>your board</small></div><div class="board-status"><span>WHITE TO MOVE</span><strong>${state.lastMove.length?'LAST: '+state.lastMove.join('–').toUpperCase():'STARTING POSITION'}</strong><span>♟ CLASSIC</span></div></div>`}
function fenFromBoard(){let b=state.board||startBoard,map={'♜':'r','♞':'n','♝':'b','♛':'q','♚':'k','♟':'p','♖':'R','♘':'N','♗':'B','♕':'Q','♔':'K','♙':'P'},rows=[];for(let r=8;r>=1;r--){let empty=0,row='';for(let f=0;f<8;f++){let x=b[files[f]+r];if(!x)empty++;else{if(empty){row+=empty;empty=0}row+=map[x]}}if(empty)row+=empty;rows.push(row)}return rows.join('/')+' w KQkq - 0 1'}
function enginePanel(){let e=state.engine;return `<div class="engine ${e.status==='thinking'||e.status==='online'?'engine-live':''}"><div class="engine-head"><span>STOCKFISH 10 · WEB WORKER</span><span>${e.status.toUpperCase()}</span></div><div class="eval">${e.eval}</div><p class="pv">${e.pv}</p><div class="engine-line"><label>Depth <input id="depth" type="range" min="8" max="18" value="${e.depth||14}"></label><button class="outline" data-action="stockfish">${e.status==='thinking'?'CALCULATING…':'ANALYZE POSITION'}</button></div></div>`}
analyze=function(){let b=state.board||clone(startBoard);return `<section class="page"><div class="section-title"><p class="eyebrow">ANALYSIS WORKSPACE</p><h1>A board built for thinking.</h1><p>Move pieces, check a line with Stockfish, then ask what the position is really about.</p></div><div class="analysis-layout"><div class="board-wrap">${boardHtml(b)}<div class="board-controls"><button class="outline" data-action="reset">RESET</button><button class="outline" data-action="fen">LOAD FEN</button><button class="primary" data-action="stockfish">♟ ANALYZE</button></div>${enginePanel()}</div>${coachPanel()}</div></section>`}
call=function(){let hasCam=!!state.media.camera;return `<section class="call-page"><aside class="call-avatar"><div class="avatar-large">♞</div><p class="call-title">ChessCoach AI</p><span class="speaking">● ${state.media.voice?'VOICE READY':'VOICE OFF'}</span>${hasCam?'<video id="cameraPreview" class="camera-preview" autoplay muted playsinline></video>':'<div class="call-empty-camera">Your camera is off</div>'}<button class="outline voice-toggle" data-action="voice">${state.media.voice?'VOICE ON':'VOICE OFF'}</button></aside><div class="call-board">${boardHtml(state.board||clone(startBoard))}</div><aside class="transcript"><h3>LIVE TRANSCRIPT</h3><div class="alert-banner">Your call is private by default. Nothing starts recording or sharing until you press a control.</div>${state.chat.map(m=>`<div class="message ${m.role}"><b>${m.role==='coach'?'COACH':'YOU'}</b><br>${m.text}</div>`).join('')}<p class="permission-note">Microphone uses your browser permission. Camera is a local preview. The browser voice is a demo voice; connect a realtime AI provider for live model speech.</p></aside><footer class="call-controls"><div><button class="round-control ${state.media.mic?'active':''}" data-action="microphone">🎙</button><span class="control-label">MIC</span></div><div><button class="round-control ${hasCam?'active':''}" data-action="camera">📷</button><span class="control-label">CAMERA</span></div><div><button class="round-control" data-action="share">▱</button><span class="control-label">SHARE</span></div><div><button class="round-control" data-action="stockfish">♟</button><span class="control-label">ENGINE</span></div><div><button class="round-control end" data-action="endcall">☎</button><span class="control-label">END</span></div></footer></section>`}
function courses(){let c=[['01','Calculation Foundations','Find forcing moves, make a candidate list, then calculate cleanly.'],['02','The Open Sicilian','Learn the structures, plans and tactical pressure points.'],['03','Rook Endgames','King activity, Lucena, Philidor, and practical defense.'],['04','Game Review Method','Turn a loss into a useful, repeatable training habit.']];return `<section class="page"><div class="section-title"><p class="eyebrow">CHESSCOACH CURRICULUM</p><h1>Learn with a plan, not a feed.</h1><p>Short courses with interactive board work and coach prompts.</p></div><div class="course-grid">${c.map(x=>`<article class="panel course-card"><span class="number">COURSE ${x[0]}</span><h2>${x[1]}</h2><p>${x[2]}</p><button class="outline" data-action="course" data-course="${x[1]}">START COURSE →</button></article>`).join('')}</div></section>`}
views.courses=courses;
function attachCamera(){let v=document.querySelector('#cameraPreview');if(v&&state.media.camera){v.srcObject=state.media.camera;v.play().catch(()=>{})}}
function say(text){if(!state.media.voice||!('speechSynthesis'in window))return;window.speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(text.replace(/[“”]/g,''));u.rate=.96;u.pitch=.92;window.speechSynthesis.speak(u)}
async function startMic(){if(state.media.mic)return stopMic();try{let stream=await navigator.mediaDevices.getUserMedia({audio:true});state.media.mic=stream;let R=window.SpeechRecognition||window.webkitSpeechRecognition;if(R){let rec=new R();rec.continuous=true;rec.interimResults=true;rec.onresult=e=>{if(!e.results[e.resultIndex].isFinal)return;let t=e.results[e.resultIndex][0].transcript.trim();if(t)askCoach(t,true)};rec.onerror=()=>{};rec.start();state.media.recognition=rec}render()}catch(e){alert('Microphone permission was not granted. You can still type to your coach.')}}
function micConsent(){if(state.media.mic)return stopMic();openModal('Use your microphone?',`<p>ChessCoach AI will ask your browser for microphone access so it can transcribe what you say during this call. Audio is not recorded or sent anywhere by this demo unless you later connect a realtime AI provider.</p><button class="primary" id="allowMic">YES, ALLOW MICROPHONE</button><button class="outline" id="notNow">NOT NOW</button>`,()=>{document.querySelector('#allowMic').onclick=()=>{closeModal();startMic()};document.querySelector('#notNow').onclick=closeModal})}
async function askCoach(raw,fromVoice=false){let text=escapeHtml(raw);state.chat.push({role:'user',text});let reply='Before we chase the engine, name the forcing moves: checks, captures, and threats. Then tell me which piece is least active.';let endpoint=window.CHESSCOACH_COACH_ENDPOINT;if(endpoint){try{let res=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:raw,fen:fenFromBoard(),mode:'teacher'})});if(res.ok){let data=await res.json();reply=data.reply||reply}}catch(e){reply='Your hosted coach endpoint is unavailable, so I’m staying in local coaching mode. What is the opponent threatening?'}}state.chat.push({role:'coach',text:reply});if(fromVoice||state.page==='call')say(reply);render()}
function stopMic(){state.media.mic?.getTracks().forEach(t=>t.stop());state.media.mic=null;state.media.recognition?.stop();state.media.recognition=null;render()}
async function startCamera(){if(state.media.camera){state.media.camera.getTracks().forEach(t=>t.stop());state.media.camera=null;render();return}try{state.media.camera=await navigator.mediaDevices.getUserMedia({video:true,audio:false});render();setTimeout(attachCamera,0)}catch(e){alert('Camera permission was not granted. Camera remains off.')}}
function runStockfish(){if(state.engine.status==='thinking')return;state.engine.status='thinking';state.engine.eval='…';state.engine.pv='Stockfish is loading in a background worker.';render();let depth=document.querySelector('#depth')?.value||14;if(!state.engine.worker){try{state.engine.worker=new Worker('engine-worker.js');state.engine.worker.onmessage=e=>{let d=e.data;if(d.type==='error'){state.engine.status='unavailable';state.engine.pv=d.message;render();return}let line=d.data||'';if(/info depth/.test(line)){let m=line.match(/depth (\d+).*?score (cp|mate) (-?\d+).*? pv (.+)/);if(m){state.engine.status='online';state.engine.depth=m[1];state.engine.eval=m[2]==='mate'?'M'+m[3]:(Number(m[3])/100>0?'+':'')+(Number(m[3])/100).toFixed(2);state.engine.pv=m[4];render()}}};state.engine.worker.onerror=()=>{state.engine.status='unavailable';state.engine.pv='The Stockfish worker failed to start in this browser.';render()}}catch(e){state.engine.status='unavailable';state.engine.pv='Web Workers are unavailable in this browser.';render();return}}state.engine.worker.postMessage({type:'analyze',fen:fenFromBoard(),depth})}
const originalAction=action;action=function(a){if(a==='stockfish')return runStockfish();if(a==='microphone')return micConsent();if(a==='camera')return startCamera();if(a==='voice'){state.media.voice=!state.media.voice;render();return}if(a==='endcall'){stopMic();if(state.media.camera){state.media.camera.getTracks().forEach(t=>t.stop());state.media.camera=null}setPage('dashboard');return}if(a==='course'){let n=document.querySelector('[data-course]')?.dataset.course||'this course';state.chat.push({role:'coach',text:`Great choice. We’ll begin ${n} with a board exercise. Tell me your first candidate move.`});setPage('analyze');return}return originalAction(a)};
const originalBind=bind;bind=function(){originalBind();attachCamera();let form=document.querySelector('#chatForm');if(form)form.onsubmit=e=>{e.preventDefault();let i=document.querySelector('#chatInput');if(i.value.trim())askCoach(i.value)};document.querySelectorAll('[data-course]').forEach(b=>b.onclick=()=>{let n=b.dataset.course;state.chat.push({role:'coach',text:`Great choice. We’ll begin ${n} with a board exercise. Tell me your first candidate move.`});setPage('analyze')})};
render();
